### ISSUE TITLE
View size

### ISSUE THREAD

**Issue by ghost** [naoyashiga/RPModalGestureTransition#1]
@naoyashiga How can I change the size of the view that pops up? To make it almost fill the whole screen?

**Comment by naoyashiga** [comment]
https://github.com/naoyashiga/RPModalGestureTransition/blob/master/RPModalGestureTransition/BackgroundPresentationController.swift#L11

``` swift
struct ModalSizeRatio {
    static let width: CGFloat = 1.0
    static let height: CGFloat = 1.0
}
```

Please try! 🙏

**Comment by ghost** [comment]
@naoyashiga Worked! Thanks 😃
